code/services/QueuedJobService.php
=> FIX: This always runs

code/controllers/QueuedJobsAdmin.php, code/dataobjects/QueuedJobDescriptor.php
- Admin can delete or edit jobs
- Non-admins can view jobs as readonly in the CMS
=> API Improve queuedjobs admin

README.md, _config/queuedjobs.yml, code/dataobjects/QueuedJobRule.php, code/jobs/DoormanProcessManager.php, code/jobs/DoormanQueuedJobTask.php, code/services/QueuedJobService.php, code/tasks/ProcessJobQueueChildTask.php, code/tasks/ProcessJobQueueTask.php, code/tasks/engines/BaseRunner.php, code/tasks/engines/DoormanRunner.php, code/tasks/engines/QueueRunner.php, code/tasks/engines/TaskRunnerEngine.php, composer.json, docs/en/configuring-multi-process-execution.md
Rebased from https://github.com/silverstripe-australia/silverstripe-queuedjobs/pull/47
=> Added additional core engine

code/QJUtils.php, code/controllers/QueuedJobsAdmin.php, code/dataobjects/QueuedJobDescriptor.php, code/extensions/ScheduledExecutionExtension.php, code/forms/GridFieldQueuedJobExecute.php, code/jobs/DeleteObjectJob.php, code/jobs/GenerateGoogleSitemapJob.php, code/jobs/ScheduledExecutionJob.php, code/tasks/CreateQueuedJobTask.php, code/tasks/PublishItemsTask.php, code/workers/JobWorker.php
=> remove more tailing spaces

code/jobs/PublishItemsJob.php
Adding a phpdoc block for title
=> Adding a phpdoc block

code/services/QueuedJobService.php
=> BUG fix merge regressions from https://github.com/silverstripe-australia/silverstripe-queuedjobs/pull/49/

code/dataobjects/QueuedJobDescriptor.php, code/tasks/CreateQueuedJobTask.php
=> adding space

code/controllers/QueuedJobsAdmin.php, code/dataobjects/QueuedJobDescriptor.php, code/services/QueuedJobService.php, code/tasks/CreateQueuedJobTask.php, code/tasks/PublishItemsTask.php
using tabs instead of spaces for indentation
=> converting spaces as indentation to tabs

.travis.yml
To help prove this module is 3.2 compatible. :)
=> Ensure tests for 3.2 and php 5.6 exist

code/QJUtils.php, code/services/QueuedJobService.php
This is a squash and rebase of #17
=> BUG Fix error logging passing invalid errcontext

tests/QueuedJobsTest.php
Fix bug where DB is not required for tests
=> FIX Tests now use DB when needed

code/services/QueuedJobService.php, tests/QueuedJobsTest.php
=> FIX CheckJobHealth only checks the health of jobs in the current queue

src/Controllers/QueuedJobsAdmin.php
=> Making inclusion-duration of finished jobs configurable

composer.json
Got a warning when doing a composer update, this should fix it
=> Vendor update

.travis.yml
builds on #139 to make the travis install time a bit faster
=> Make travis more efficient

src/Controllers/QueuedJobsAdmin.php, src/DataObjects/QueuedJobDescriptor.php
=> FIX Update "Create new job" button to use bootstrap and escape HTML in messages in GridField

src/Services/AbstractQueuedJob.php, src/Services/QueuedJob.php, src/Services/QueuedJobService.php, src/Tasks/ProcessJobQueueTask.php
Some SS4 improvements that are required
=> Adding SS4 compatibility for SubSites, Config and Injectable

src/Tasks/Engines/DoormanRunner.php
So that PHP is not used to interpret the sake bash script.
=> FIX: Clear the binary field

src/Tasks/Engines/DoormanRunner.php
=> NEW Allow ProcessManager log path to be configurable

src/Tasks/Engines/DoormanRunner.php
We would like to replace the manager with an instance of another class.
=> NEW: Ability to inject a different process manager class.

src/Tasks/Engines/DoormanRunner.php
hi
A couple of minor fixes re SS4.1 that I ran into today
Cheers
Gordon
=> SS41 Fixes

src/Services/QueuedJobService.php
=> FIX: Ensure null->ID is not evaluated

src/Jobs/GenerateGoogleSitemapJob.php
Also implements minor tweaks for other broken logic in this class.
Resolves #187
=> FIX Use correct namespaces for Versioned and ErrorPage

code/services/QueuedJobService.php
Fixes issue https://github.com/symbiote/silverstripe-queuedjobs/issues/228 for 3.0 (and above after merging up).
=> Fix(QueuedJobService): Valid $messages data being overwritten

src/Controllers/QueuedJobsAdmin.php
=> NEW Remove duplicated Jobs header in admin, and remove GridField toolbar header

src/Services/QueuedJobService.php
- Don’t send the email if there’s no admin email address. It failed
previously, but this suppresses the error message.
- Lower the severity of the “job restarted” message to warning, as in
theory it is self-healing
- Include job ID# in the message.
=> NEW: Improve stalled-job messages

src/Services/QueuedJobHandler.php, src/Services/QueuedJobService.php
Batches output using BufferHandler so we don't constantly write logs to the database.
=> Batch log messages for every 100 file

src/Controllers/QueuedTaskRunner.php
* Added an option to have queued only tasks via configuration
* this is useful for tasks that take too long to run via browser
* especially useful when task produce output as this will get captured in the queued job instead of timing out via browser
=> Queued only tasks configuration added.

README.md
README updated as per issue #251
=> updated README to fix incorrect cronjob entries

src/Services/QueuedJobService.php
At the moment setting this to false does not work since it defaults to the admin address. This adds support to disable it by explicitly setting it to false.
=> Allow queued_job_admin_email to be disabled

README.md
* added documentation on queued jobs related unit tests
=> Documentation on queued jobs related unit tests.
