symbiote/silverstripe-queuedjobs

code/services/QueuedJobService.php
tests/QueuedJobsTest.php

Check the affected rows when setting JobStatus via DB::query() instead
of write(). If nothing was affected, then bail out as there's nothing to be done.

BUG Two processes can potentially start the same job due to race cond

---

tests/ScheduledExecutionTest.php

Fixes these warnings: 
Deprecated: Config static TestScheduledDataObject::$extensions must be marked as private
Deprecated: Config static TestScheduledDataObject::$db must be marked as private

Fix deprecation errors on static vars

---

code/dataobjects/QueuedJobDescriptor.php

Because DropdownField needs an associative array not an indexed one.

BUG Fix dropdown not selecting correct status

---

README.md
code/dataobjects/QueuedJobDescriptor.php
code/services/QueuedJobService.php
code/tasks/ProcessJobQueueTask.php
tests/QueuedJobsTest.php

BUG Better memory detection
BUG Correct usage of configurable options in QueuedJobService
BUG Corrected "ResumeCount" to "ResumeCounts"
Another potential solution to https://github.com/silverstripe-australia/silverstripe-queuedjobs/issues/41
@nyeholt would you be able to please review my logic? I've written up a complete unit test covering job restart and I believe that my logic is correct, but it deserves some critique.
I have replaced the requirement that StepsProcessed must be > 0 in order to be restartable, and instead changed LastProcessedCount to default to -1 (and is set to 0 during checkJobHealth on jobs that are suspected of requiring restart). This means that although jobs won't restart immediately, if no work is done on them they will eventually restart.

API Better restarting of stalled jobs (when StepsProcessed == 0)

---

code/controllers/QueuedJobsAdmin.php

When in the CMS as a user I usually care about more recent log messages than older ones. This is especially the case when reloading the page to watch for updates from the task. If it's on the last page, GridField currently doesn't remember the page.

Order jobs by latest created

---

README.md
code/services/QueuedJobService.php

Fix for #46 - documented a workaround for the jobqueue health check mistakenly marking a job
as being paused (ie set currentStep = -1).
Tweaked some code in QueuedJobDescriptor to ensure that only jobs with a
StepsProcessed count > 0 are considered as needing a 'restart' instead of a
'setup'

DOC document job health check workaround

---

code/tasks/ProcessJobQueueTask.php
code/tasks/engines/BaseRunner.php

ProcessJobQueueTask has an option to list current jobs but was missing the actual code. It seems to have been refactored away accidentally (#80). This fix restores the indented functionality.

Readded function to list current jobs in ProcessJobQueueTask

---

code/services/QueuedJobService.php

Little typo in the public $queueRunner property.

Typo in QueuedJobService public property queueRunner

---

composer.json

After some local testing, it seems that silverstripe-cms doesn't really need to be a requirement for this project.

Remove CMS as composer requirement

---

code/services/QueuedJobService.php

The documentation suggests that the correct config variable for error emails is queued_job_admin_email, however, the code in the constructor of the QueuedJobService is set to queued_jobs_admin_email/

Fix reference to queued job admin email

---

code/QJUtils.php
code/services/QueuedJobService.php

Fixes https://github.com/silverstripe-labs/silverstripe-fulltextsearch/issues/111
This causes errors because SS_Backtrace cannot parse these arrays as being valid backtraces.

BUG Remove invalid backtraces from errcontext

---

README.md

Looking at ProcessJobQueueTask.php - getQueue(), queue should be one of immediate, queued or large

fix long job cron example in readme

---

composer.json

Just coz I need it for legacy :(
This is literally the only branch without a composer.json so I do think we should have it

NEW Add composer file

---

code/services/AbstractQueuedJob.php

These methods should be in every extension of the abstract class and should therefore be actual abstracts.

Make the required methods abstracts

---

code/controllers/QueuedJobsAdmin.php

This hook is normally in ModelAdmin. Since it was missing it was not possible to edit the fields in QueuedJobsAdmin.

added updateEditForm hook

---

README.md

Added a note that the CleanupJob needs to be triggered manually once for it to start running every day.

Updates: Readme

---

composer.json

Update asyncphp/doorman to 3.0 to be compatible with SilverStripe 4.0

FIX: Update doorman to 3.0 in composer.json

---

src/Services/QueuedJobService.php

FIX Issue where setting isComplete=true during 'setup()' or 'prepareForRestart()' causes the job to say its "Running" indefinitely.

FIX Issue where setting isComplete=true during 'setup()' or 'prepareForRestart()' causes the job to say its "Running" indefinitely.

---

README.md
code/services/QueuedJobService.php
composer.json

**WARNING: This fix seems to mess with composer.json in unintended ways, what should I be doing here?**
fix(JobErrorHandler): Fix bug where deprecation / variable set in if-statement would always cause zero outputting of errors to console. Modified logic to align with Core silverstripe functions.
Culprit:
https://github.com/silverstripe-australia/silverstripe-queuedjobs/blob/master/src/Services/QueuedJobService.php#L969

fix(JobErrorHandler): Output error messages in console again

---

code/jobs/CleanupJob.php

Before this patch, if there were no jobs to clean up, no new CleanupJob
was scheduled because of a premature return in process().

Always enqueue a new CleanupJob when complete

---

.travis.yml
_config.php
codecov.yml
composer.json
phpunit.xml.dist
src/Services/JobErrorHandler.php
src/Services/QueuedJobService.php
src/Tasks/CreateQueuedJobTask.php
src/Tasks/DummyQueuedJob.php
tests/AbstractTest.php
tests/CleanupJobTest.php
tests/QueuedJobsAdminTest.php
tests/QueuedJobsTest.php
tests/QueuedJobsTest/TestQJService.php
tests/ScheduledExecutionTest.php

* Move DummyQueuedJob and JobErrorHandler into their own files
* Apply PSR-2 linting to remaining files
* Remove code coverage run for now
I've removed the standard code coverage run from the Travis config template, which normally uses phpdbg on PHP 7.1 - I've done this because there are two integration tests that consistently fail with coverage runs enabled. Using Xdebug we still have a failure but in a different integration test. I'll log this issue separately.

Update Travis configuration, add namespaces to Test classes, fix bug with QJService shutdown function in tests

---

code/services/ImmediateQueueHandler.php

This API is relied upon in `QueuedJobHandler` and causes fatal errors if you try to use the immediatequeuehandler.

Add scheduledJob to ImmediateQueueHandler

---

LICENSE
README.md
lang/ar.yml
lang/de.yml
lang/eo.yml
lang/fi.yml
lang/hr.yml
lang/mi.yml
lang/ru.yml
lang/zh.yml
src/Controllers/QueuedJobsAdmin.php
src/Jobs/CleanupJob.php
src/Services/ImmediateQueueHandler.php
src/Services/QueuedJobService.php
templates/QueuedJobsDefaultJob.ss
tests/QueuedJobsTest.php
tests/QueuedJobsTest/TestExceptingJob.php

Merge 3 -> master

---

.travis.yml

PHP 5.3 is unsupported on trusty in Travis, and the precise distro will be removed in a few months

Remove PHP 5.3 from Travis config, add 7.0 and 7.1

---

.travis.yml
README.md
_config/queuedjobs.yml
composer.json
scripts/lsyncd-config.sample
scripts/queue_processor.init
scripts/run-queued-jobs.sh
src/Controllers/QueuedJobsAdmin.php
src/DataObjects/QueuedJobDescriptor.php
src/Tasks/Engines/DoormanRunner.php

Summary of changes:
* Convert to vendor module -> module will be installed into `vendor/symbiote/silverstripe-queuedjobs`
* Images directory will be "exposed" (symlinked into resources folder for public access outside of vendor folder)
* Added PHP 7.2 to the Travis build matrix
* Update readme examples and file paths that reference cli-script.php to use `vendor/bin/sake`

NEW Convert to vendor module, update use of cli-script with sake and some readme examples

---

src/Controllers/QueuedJobsAdmin.php

This means future abstract classes (such as the one in https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/70) won't be available to be "run" from the admin interface.

filter out non-instantiable classes from QueuedJobsAdmin dropdown

---

src/Jobs/GenerateGoogleSitemapJob.php

Legacy code updates required for GenerateGoogleSitemapJob.php to run without error.

FIX: Fixes #156 Addition of missing `TempFolder` and `Environment`

---

_config/taskrunner.yml
code/controllers/QueuedTaskRunner.php
code/dataobjects/QueuedJobDescriptor.php
code/jobs/RunBuildTaskJob.php
code/services/QueuedJobService.php
code/tasks/DeleteAllJobsTask.php
code/tasks/engines/BaseRunner.php

This adds a couple of items:
* A job type RunBuildTaskJob, that will run a single build task
* A QueuedTaskRunner, that overrides the default dev/tasks admin in non-CLI mode, to allow queuing of build tasks by default
The result is that when queued jobs is installed, web management of build tasks will by default happen on background job queues. This will simplify the deployment of SilverStripe sites to servers where the dev team don’t have SSH access.
Fixes #150

NEW: Allow queueing of build tasks

---

src/Services/QueuedJobService.php

Since the SS4 upgrade, you can't generate a job via CLI because of this error:
```
PHP Notice:  Trying to get property of non-object in /vagrant/www/vendor/symbiote/silverstripe-queuedjobs/src/Services/QueuedJobService.php on line 186
```
For example, in staticpublishqueue, I can't run the [StaticCacheFullBuildTask](https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/master/src/Task/StaticCacheFullBuildTask.php#L87) via CLI successfully. This is because in the SS3 version, the fallback if there was no `$userID` passed in was `Member::getCurrentUserID()` - which would return `0` if there was no member i.e. it was run via CLI. Since this has been changed to `Security::getCurrentUser()->ID`, we get the above error. This PR re-introduces the fallback.

reinstate fallback to 0 for runasID post-ss4

---

src/Services/QueuedJobService.php

`QueuedJobService::queueJob()` is making the assumption that a `User` will always be provided or available through `Security::getCurrentUser()`, but `QueuedJobService::runJob()` does not require a `User` to be set, and a `User` might not need to be provided for Jobs queued through a cron.

Check that Security::getCurrentUser() returns not null before accessing property

---

src/Services/QueuedJobService.php

I have extended fields on my `QueuedJobDescriptor` record, and I'm needing to update these fields when particular `Exceptions` are thrown as part of `Job::process()`. I couldn't see a way to access the `Descriptor` from within the `Job` - these extension points fill that gap.

Add extensions points to QueuedJobService.

---

src/Services/QueuedJobService.php

Related issue:
https://github.com/symbiote/silverstripe-queuedjobs/issues/168

Set "RunAs" User to Security rather than SESSION. Fixes #168

---

src/Services/QueuedJobService.php

`RaygunHandler` requires that context is provided to it. This can either be the `Exception` itself, or values for "line" and "file".
`QueuedJobService`
Line `702` or `806`: An `Exception` is thrown and caught.
Line `704` or `808`: Logs the Exception message (*only* the message) to `Monolog\Logger::error()`.
`Monolog\Logger`
Line `614`: `error()` accepts `string $message` and `array $context` (please note, no `$context` was passed above, so this is an empty `array`)
Line `616`: `error()` calls `addRecord()` with error level, message, and context as it's params.
Line `322`: `addRecord()` creates `$record`:
```
$record = array(
'message' => (string) $message,
'context' => $context,
'level' => $level,
'level_name' => $levelName,
'channel' => $this->name,
'datetime' => $ts,
'extra' => array(), …
```

Log QueuedJob errors with context provided.

---

src/Controllers/QueuedJobsAdmin.php

Based on the emoji tally in the [related issue](https://github.com/symbiote/silverstripe-queuedjobs/issues/162), which I interpret to make the checklist font icon the crowd's favourite, it is used as the menu icon. This resolves #162 
It looks like that:
It works well with the other menu icons
The font icon was introduced to the admin module in https://github.com/silverstripe/silverstripe-admin/commit/d5d022ec752a38c7e931694ea6fa660f2fae85c4, so an update to the admin module version dependency might be required.
@clarkepaul

Replace 'clipboard-pencil' font icon with 'checklist' font icon

---

src/Controllers/QueuedJobsAdmin.php

`QueuedJobService::queueJob` already has a type hint for QueuedJob in its arguments, so this change just introduced a slightly earlier check that would prevent a fatal error from being thrown if it reached that far.
Also swap a deprecated method for its new equivalent.

FIX Swap deprecated Member::currentUser and check that $jobType is a job

---

tests/ScheduledExecutionTest.php

Fixes bug where tests fail towards the end of each hour.

FIX Mock current date and time in scheduled execution test

---

src/Services/QueuedJobService.php

Fixed a situation where unsetting a user would generate a PHP notice because we are trying to access object property of null. This is quite annoying as one notice per job is created.

Fixed a case where original user was missing when unsetting a user.

---

src/Services/QueuedJobService.php
tests/QueuedJobsTest.php

Fixes https://github.com/symbiote/silverstripe-queuedjobs/issues/190
This PR changes a couple of things:
* use assertCount for countable lists
* correct docblock return type for getJobList (returns a list not a descriptor)
* adds a couple of PHPDoc hints for class types
* removes deprecated `Config::inst()->update()` use
* removes second argument to addMessage, which doesn't exist any more

FIX Allow integration/unit tests to use more memory, update assertions and docblock tweaks

---

src/Extensions/ScheduledExecutionExtension.php

When applying this extension to a scaffolded dataobject, the fields already exist in the CMS so when this runs and tries to re-add SilverStripe will throw a warning indicating those fields already exist. This ensures that the fields have been removed first.

Ensure extension fields don't exist before adding them

---

src/Services/QueuedJobService.php

As per #199 update `markstarted()` and `hasPassedTimeLimit()` to use the `getTimestamp()` method instead of formatting the time.

Update QueuedJobService to use timestamps

---

tests/ScheduledExecutionTest.php

Refactored the test that _sometimes_ fails. It now uses `DateTime`s to and `DateInterval` to accurately compare time differences, and allows for up to 1 second of "fuzzyness". 
Testing microseconds would have been nicer but `DateInterval::$f` is not available until 7.1 🙁

Updated test that sometimes fails to have a little leniency

---

src/Jobs/DoormanQueuedJobTask.php
tests/Jobs/DoormanQueuedJobTaskTest.php
tests/Jobs/DoormanQueuedJobTaskTest.yml

See #204 and #105
This means that when Doorman's runner detects a stalled job which is then picked up in a different process and completed, then the original doesn't continue to loop looking for jobs that aren't "cancelled" and life forever because the job is now "complete"
Resolves #105, but I'm still looking into the reason the jobs are stalling in the first place for #204

FIX Doorman's 'is cancelled' criteria now included completed jobs, preventing infinite processes

---

docs/en/configuring-multi-process-execution.md
src/Services/QueuedJobService.php
src/Tasks/CreateQueuedJobTask.php
src/Tasks/Engines/BaseRunner.php
src/Tasks/Engines/DoormanRunner.php
src/Tasks/ProcessJobQueueChildTask.php

Also updates the namespace reference in the Doorman configuration docs for Injector and switches the code block formatting to use GitHub flavoured markdown

FIX Remove use of deprecated DB::getConn(), update broken doc blocks etc

---

README.md
src/Services/QueuedJobService.php
src/Tasks/CheckJobHealthTask.php

Resolves #213
This will do nothing by default. However you can now disable automated health checks with a config setting. There is also a new build task provided to do health checking - this can be set up as a cron.

NEW Allowing disabling health checks - adding a task for it

---

src/Services/QueuedJobService.php
templates/QueuedJobsStalledJob.ss

Resolves #25 
The new template would look like this:
```
Hi,
A job named Content Review Notification Job appears to have stalled. It will be stopped and restarted, please login to make sure it has continued
Job ID: 2
Log in to http://cwp21.localhost/ to see further details and take any necessary actions.
```
Wording is from QueuedJobsDefaultJob.ss (existing).
Note: I can't receive any of these local emails that are fired from my local environment to my Gmail account, but I've validated that the body is rendered and that the email send result is true.

NEW Include website URL in stalled jobs email as well as job ID

---

_config/tests.yml
src/Dev/State/QueuedJobsTestState.php

Many modules using this module will need to disable this handler in their own unit tests. This PR adds a TestState which will do it globally whenever the module is installed in the project.

FIX Add queuedjobs test state to disable the shutdown handler during unit tests

---

src/QJUtils.php
src/Services/QueuedJobService.php

Issue: https://github.com/silverstripe/silverstripe-framework/issues/8424

FIX Replace Convert JSON methods with json_* methods, deprecated from SilverStripe 4.4

---

README.md
code/jobs/CleanupJob.php

Adds the config option `query_limit` for the CleanupJob (and readme addition).
I would suggest a new release for this change.

CleanupJob query_limit

---

_config/legacy.yml

This provides class-name remapping for upgrades from SilverStripe 3 to
SilverStripe 4, as per Step 10 of the [upgrade guide](https://docs.silverstripe.org/en/4/upgrading/#step10).

Provide legacy class-name map for SilverStripe 4

---

src/Controllers/QueuedJobsAdmin.php
src/DataObjects/QueuedJobDescriptor.php

- Translate the job type from a number to a string
- Add “finished”, which can be useful for seeing job duration

NEW: Improve job list in admin/queuedjobs

---

src/Jobs/CleanupJob.php
src/Services/QueuedJobService.php

The config was not namespaced, so it would not have re-enqueued itself. I have also added some PHPDoc hints to assist with IDE type hinting in QueuedJobService.

FIX Cleanup tasks now uses Configurable and correctly re-enqueues itself

---

README.md
phpcs.xml.dist
src/Controllers/QueuedJobsAdmin.php
src/Controllers/QueuedTaskRunner.php
src/DataObjects/QueuedJobDescriptor.php
src/Extensions/ScheduledExecutionExtension.php
src/Jobs/CleanupJob.php
src/Jobs/GenerateGoogleSitemapJob.php
src/Jobs/ScheduledExecutionJob.php
src/QJUtils.php
src/Services/AbstractQueuedJob.php
src/Services/ImmediateQueueHandler.php
src/Services/QueuedJobService.php
src/Tasks/CreateQueuedJobTask.php
src/Tasks/DummyQueuedJob.php
src/Tasks/Engines/BaseRunner.php
src/Tasks/Engines/DoormanRunner.php
src/Tasks/ProcessJobQueueChildTask.php
src/Tasks/ProcessJobQueueTask.php
src/Workers/JobWorker.php
tests/QueuedJobsAdminTest.php
tests/QueuedJobsTest.php
tests/QueuedJobsTest/TestQueuedJob.php
tests/ScheduledExecutionTest.php

* Prefer DBDatetime over time()/date()
* Prefer ClassName::singleton() over singleton(ClassName)
* Fix incorrect doc block argument and return types
* Remove direct calls to DataList, use ORM filters from base class
* Reduce line lengths to 120 characters maximum
* Switch to PSR-12 as a base ruleset and run automated linting
* Fix dev controller where "admin" was hard coded, should be dynamic

NEW Some minor touchups to code to adhere to current SilverStripe best practices

---

src/Services/QueuedJobService.php

When queuing default job, log to info() instead of error()

minor - log information to info instead of error

---

src/Services/AbstractQueuedJob.php
src/Services/QueuedJob.php
src/Services/QueuedJobService.php
src/Tasks/Engines/DoormanRunner.php

Multiple extensibility options added:
* `getRunAsMemberID` configuration - this allows the jobs to be run without a user (job level configurable)
* `max_init_jobs` option added - prevents too many jobs to be in the `init` state
* `updateJobDescriptorBeforeQueued ` extension point added - this allows custom DB columns to be populated before the job is queued (used for data that can't be present in the serialized job data like identifiers for example)
* `updateJobDescriptorAndJobOnCompletion` extension point added - this is useful for `dependent` jobs, i.e. jobs that are queued only after other jobs finish
* PHP 7 exception handling added - type errors were not handled properly before
Compatibility notes:
* jobs that do not extend `AbstractQueuedJob` need to add the `getRunAsMemberID` …

Extensibility options improvements.

---

src/Services/QueuedJobHandler.php

The severity was set to INFO, which is a bug: It masks the actual severity of the log message,
for example ERROR or ALERT.
~Recording the datetime of addMessage() as the current datetime is also a bug:
It masks the actual date when the message was recorded, which could be many seconds
earlier due to message batching. This can in turn mask issues around slow executions,
e.g. during the file migration tasks for which this layer was introduced.
Note that the QueuedJob interface which AbstractQueuedJob implements does not have this new third argument. There's already precedent for adding optional arguments to the interface with $severity.~

Log severity and original date in queue messages

---

README.md
_config/queuedjobs.yml
src/Extensions/MaintenanceLockExtension.php
src/Services/QueuedJobService.php
src/Tasks/Engines/DoormanRunner.php
src/Tasks/Engines/QueueRunner.php
src/Tasks/ProcessJobQueueTask.php
tests/MaintenanceLockTest.php

**Queued jobs pause setting added**
* this new feature adds a UI to `SiteConfig` which allows the jobs queue to be paused
* this is a `soft` pause, which means it actually lets the running jobs to finish, but prevents new jobs from starting
* very useful for planned downtime
* note that the maintenance lock status is not saved in DB which is intentional
* this is because downtime can be caused by DB restore operation which changes the whole DB
* pausing the jobs the DB restore is very helpful when moving `prod` DB to other `non-prod` environments as it prevents possible data corruption (the jobs can start running before the DB restoration is complete)
* also, some jobs may need to be cleared or updated when moved to another environment (such as absolute URLs), this can be done before the …

Queued jobs pause setting added.

---

src/Interfaces/UserContextInterface.php
src/Services/AbstractQueuedJob.php
src/Services/QueuedJob.php
src/Services/QueuedJobService.php

Fixes https://github.com/symbiote/silverstripe-queuedjobs/issues/261
Followup to https://github.com/symbiote/silverstripe-queuedjobs/pull/247
`UserContextInterface` functionality separated out so it would prevent a breaking change.

User context interface separated out of QueuedJob interface.

---

phpcs.xml.dist
src/Controllers/QueuedJobsAdmin.php
src/DataObjects/QueuedJobDescriptor.php
src/Services/QueuedJobService.php
src/Tasks/CheckJobHealthTask.php
tests/QueuedJobsAdminTest.php

Creating new Job in CMS Admin ignores Start at (after) field 
- this cause problem in production: instead of delayed run, the job/task is executed almost immediately

FIX ignored "Start After" option when creating new Queued Job in CMS

---

.travis.yml
src/DataObjects/QueuedJobDescriptor.php
src/Services/QueuedJobService.php
src/Tasks/CheckJobHealthTask.php
tests/QueuedJobsAdminTest.php

Update the QueuedJobsAdminTest to explicitly register the fake HTTPRequest with the Injector.
This is causing problems for CWP Kitchen sink because some other LeftAndMain controller gets loaded and expects a valid request, but then it fails because it can't find one.
This should fix parts of the broken builds on the Kitchen sink for 2.2 and up.

BUG Explictely register HTTPRequest with Injector in test setup

---

phpcs.xml.dist

Suppress warning linting warning about constant visibility. This can't be fixed because the module need to work with PHP 5.6

BUG Squash linting warning about constant visibility

---

src/DataObjects/QueuedJobDescriptor.php

This syntax throws notices in PHP 7.4.

FIX Replace deprecated curly brace access syntax

---

src/Services/QueuedJobService.php
src/Workers/JobWorker.php

Fixed exception handling in the case of setup() function ended up throwing.
https://github.com/symbiote/silverstripe-queuedjobs/issues/276

Exception handling fix (on broken setup()).
